Algoritmo "Avaliação Pamela 2BI (Impar ou Par MOD)"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/06/2022
Var
n:inteiro
Inicio
escreva("Digite um número: ")
leia(n)
se n mod 2 = 0 entao
escreva("O número ", n, " é par!")
senao
escreva("O número ", n, " é ímpar!")
fimse
Fimalgoritmo