Algoritmo "Avaliação Pamela 2BI (Vogal e Consoante)"

Var
Letra:caractere
Inicio
escreva("Digite uma letra: ")
leia(Letra)
se ((maiusc(Letra) >= "A") E (maiusc(Letra) <= "Z")) entao
se ((maiusc(Letra) = "A") OU (maiusc(Letra) = "E") OU (maiusc(Letra) = "I") OU (maiusc(Letra) = "O") OU (maiusc(Letra) = "U")) entao
escreval("É uma vogal")
senao
escreval("É uma consoante")
fimse
Fimalgoritmo
FIMSE